build_try:
  stage: build
  script:
    - ./gradlew :magicasakura-x:build
  except:
    - tags

build_push:
  stage: deploy
  script:
    - ./gradlew :magicasakura-x:build
    - ./gradlew :magicasakura-x:Artifactorypublish
  only:
    - tags
