build_try:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew :matisse_x:build
  except:
    - tags

build_push:
  stage: deploy
  script:
    - chmod +x ./gradlew
    - ./gradlew :matisse_x:build
    - ./gradlew :matisse_x:Artifactorypublish
  only:
    - tags
